app/models.py
#!/usr/bin/env python
#coding:utf8

from app import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


class Role(db.Model):
    #相当于create table role(id int primary key autoincrease,
    # roles string(20) unique);
    __tablename__ = "role"

    #角色设定有三个一个管理员,一个注册用户,一个是匿名用户
    id = db.Column(db.Integer,primary_key=True)
    roles = db.Column(db.String(20),unique=True)

    #相关
    users =db.relationship("User",backref="role")

    def __unicode__(self):
        return self.roles

class User(db.Model):
    __tablename__ = "user"

    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(80),unique=True)
    passwd  = db.Column(db.String(100))


    role_id = db.Column(db.Integer,db.ForeignKey("role.id"))
    article = db.relationship("Article",backref="user")



    def __unicode__(self):
        return self.username

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.passwd = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.passwd, password)




class Article(db.Model):
    #文章
    __tablename__ = "article"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200))
    content = db.Column(db.Text)
    datetm = db.Column(db.DateTime,default=datetime.utcnow())

    user_id = db.Column(db.Integer,db.ForeignKey("user.id"))
    comment = db.relationship("Comment",backref="article")

    def __init__(self,title,content, user_id):
        self.title = title
        self.content = content
        self.user_id = user_id


    def __unicode__(self):
        return  self.title



class Comment(db.Model):
    #评论
    __tablename__ = "comment"

    id = db.Column(db.Integer,primary_key=True)
    comments = db.Column(db.Text)
    datetm = db.Column(db.DateTime, default=datetime.utcnow())

    article_id = db.Column(db.Integer, db.ForeignKey("article.id"))

    def __init__(self,comments,article_id):
        self.comments = comments
        self.article_id = article_id
    def __unicode__(self):
        return self.comments

app/__init__.py
#!/usr/bin/env python
#coding:utf8



from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config


db = SQLAlchemy()


def creat_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)


    from app.main import main as lantu
    app.register_blueprint(lantu)

    return  app

app/main/__init__.py
#!/usr/bin/env python
#coding:utf8



from flask import Blueprint

main = Blueprint('main',__name__)

from app.main import errors,views

app/main/views.py
#!/usr/bin/env python
#coding:utf8

from  flask import request,redirect,render_template,url_for,make_response,session,flash

from app.main import  main
from app.models import User,Role,Article,Comment

from app import db

@main.route("/",methods=["GET","POST"])
@main.route("/index")
def index():
    if request.method == "POST":
        username = request.form.get("username")
        passwd  = request.form.get("password")

        pass_url = User.query.filter_by(username=username).first()
        if pass_url == None :
            flash("NO USER")
            return render_template("registered.html")
        try:
            password = pass_url.verify_password(passwd)
            if  password is False:
                flash("PASSWORD IS WRONG")
                return redirect(url_for("main.index"))
            else:
                session["user"] = username
                # resp = make_response(render_template("main.html" ,user=username))
                # resp.set_cookie("userid",username)
                # return resp
                return redirect(url_for("main.blog"))

        except:
            erromassage = "You password is wrong"
            return render_template("erro.html")

    else:
        return render_template("index.html")


@main.route("/registered", methods=["POST","GET"])
def registe():
    if request.method == "POST":
        username = request.form.get("loginname")
        passwd = request.form.get("password")
        user = User.query.filter_by(username=username).first()
        if user != None:
            flash( "THE USER HAS REGISTERED ")
        else:
            #这里后期写个函数,做格式校检

            new_user = User(username=username,password=passwd,role_id=2)

            db.session.add(new_user)
            db.session.commit()

            flash('You can now login.')
            return redirect(url_for('main.index'))
        return  render_template("index.html")
    else:
        return render_template("registered.html")


@main.route("/main",methods=["GET","POST"])
def blog():
    #展示内容不管是否登入都可以查看内容,如果登入可以自己修改自己内容(换个函数)
    #只是展示前10个页面,后面进行分页
    #进行搜索
    #print  session["user"]
    if request.method=="POST":
        title = request.form.get("search")
        all = Article.query.filter(Article.title.like(title)).all()
    else:
        all = Article.query.all()

    return render_template("main.html",title=all)


@main.route("/write",methods=["POST","GET"])
def write_aritle():
    user = session.get("user")
    userid = User.query.filter_by(username=user).first().id
    if request.method=="GET":
        if user != None and User.query.filter_by(username=user):
            print "this is write save session %s"%session.get("user")
            return render_template("write.html")
        else:
            return render_template("registered.html")
    #这里存入应该是带有html标签的内容以便存储信息
    if request.method =="POST":
        t = request.form.get("title")
        con = request.form.get("content")

        title = Article(title=t,content=con,user_id=userid)
        db.session.add(title)
        db.session.commit()
        return redirect(url_for("main.blog"))

@main.route("/<int:id>")
def look_aritle(id):

    aritle = Article.query.filter_by(id=id).first()
    title = aritle.title
    content = aritle.content

    p = Comment.query.get(id)
    if request.method =="POST":
        _commit = request.form.get("提交内容")
        commit_Comment = Comment(comments=_commit)
        db.session.add(commit_Comment)
        db.session.commit()
        redirect(url_for("main.look_aritle",name=id))

    return render_template("lookaritle.html",title=title,content=content,discuss=p)


@main.route('/logout')
def logout():
   # remove the username from the session if it is there

   session.pop('user', None)
   return redirect(url_for('main.index'))

app/templates/erro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   <h1>erro test</h1>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登入页面</title>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class=flashes>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    <link rel="stylesheet" type="text/css" href="../static/index.css">
</head>
<body class="bg">
    <div class="main">
        <div class="head clearfix">
            <h1 class="logo l">欢迎</h1>
            <p class="subtitle l" >分享你的世界,分享快乐</p>
        </div>
        <div class="mainContext clearfix">
            <div class="leftContext l">
                <img src="../static/eg_tulip.jpg"  alt="上海鲜花港 - 郁金香" />
            </div>
            <div class="rightContext l">
                 <form action="/" method="post">
                     <!--img src="/static/user.jpg" alt="user"-->
                    <input type="text" name="username" id="name" placeholder="用户名"><br/>
                    <input type="password" name="password" id="pd" placeholder="密码"><br>
                    <input type="submit" class="submit-btn" name="提交">
                 </form>
            </div>
        </div>

    </div>
</body>
</html>

app/templates/lookaritle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>aritle</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <strong>{{ content }}</strong>
    {% for i in p %}
       <h2>这是评论 {{ i }}</h2>
    {% endfor %}
</body>
</html>

app/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>wlcome {{ user }}</title>
</head>
<body background="">
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="../static/main.css">
</head>
<body>
	<div class="box">
		<!-- 头部 -->
		<div class="head clearfix">
			<ul class="ul1">
				<li class="on">
					<a href="javascript:;">首页</a>
				</li>
				<li class="li2">
					<form action="{{ url_for('main.blog') }}">
						<input class="int1" type="text">
						<input type="submit" value="搜索">
					</form>
				</li>
			</ul>
			<ul class="r ul2">
				<li class="li1"><img src="../static/usr_image.jpeg" alt="头像"></li>
				<li><a href="javascript:;">登录</a></li>
				<li><a href="javascript:;">注册</a></li>
			</ul>
		</div>
        <!-- 内容 -->
        <div class="content">
            <div class="content-left">
        {% for i in title %}
            {% set idt = i.id %}
            <h2><a href="/{{  idt}}">{{ i.title }}</a></h2>
            <h5>{{ i.content |truncate(500)}}</h5>
            <strong>{{ i.datetm }}</strong>
        {% endfor %}
        </div>
                <div class="right">
            <a href=""></a>
        </div>
        </div>
	</div>
</body>
</html>

app/templates/registered.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>registered</title>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class=flashes>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    <link href="../static/registered.css" rel="stylesheet" type="text/css">
</head>
<body class="bg ">

    <div class="main claerfloat">
        <form action="/registered" method="post" class="l">
            <label>用户名:</label>
            <input type="text" name="loginname" placeholder="user name"> <br>
            <label>密码&nbsp;&nbsp;:</label>
            <input type="password" name="password" placehoder="pass word"> <br>
            <input type="submit" name="submit" class="submit-btn">
        </form>

    </div>

</body>
</html>

app/templates/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>your blog {{ session.user }}</title>
</head>
<body>
    <div>
        <form action="{{ url_for("main.write_aritle") }}" method="post">
            <input type="text" value="文章标题" name="title">
            <input type="text" value="文章内容" name="content">
            <input type="submit" value="提交">
        </form>
    </div>
</body>
</html>